//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisitoringCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Products
    {
        public int Id { get; set; }
        public int Product_id { get; set; }
        public int Order_id { get; set; }
    
        public virtual order order { get; set; }
        public virtual Product Product { get; set; }
    }
}
