//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisitoringCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class visit
    {
        public int Id { get; set; }
        public int Visitor_id { get; set; }
        public int Agent_id { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public string info { get; set; }
    
        public virtual agent agent { get; set; }
        public virtual Visitor Visitor { get; set; }
    }
}
